language: python
python:
  - "3.6"
  - "3.7"
services:
  - mysql
addons:
  apt:
    packages:
      - libmysqlclient-dev
dist: xenial
cache:
  - pip
before_install:
  - pip install -U pipenv
install:
  - pipenv install --dev --deploy
script:
  - black --check .
  - python manage.py test -v 2
